import { supabase, getSupabase } from './supabase';
import type { Product } from '@/types';

// ─── Fetch active products from Supabase ───
// Images are stored as a direct URL field on the product (Firebase Storage)
export async function fetchProducts(): Promise<Product[]> {
  if (!getSupabase()) return [];

  const { data, error } = await supabase
    .from('products')
    .select('id, name, price, category, description, popular, product_images(image_url, is_primary)')
    .eq('status', 'active')
    .order('created_at', { ascending: false });

  if (error) {
    console.error('Error fetching products:', error);
    return [];
  }

  return (data || []).map((p: any) => {
    const imgs = p.product_images || [];
    const primary = imgs.find((img: any) => img.is_primary);
    const imageUrl = primary?.image_url || imgs[0]?.image_url || '/products/case-amirah.png';
    return {
      id: p.id,
      name: p.name,
      price: p.price,
      category: p.category as Product['category'],
      description: p.description || '',
      popular: p.popular || false,
      image: imageUrl,
    };
  });
}

// ─── Fetch shipping rates from Supabase ───
export async function fetchShippingRates() {
  if (!getSupabase()) return [];

  const { data, error } = await supabase
    .from('shipping_rates')
    .select('*')
    .order('wilaya_code');

  if (error) {
    console.error('Error fetching shipping rates:', error);
    return [];
  }

  return data || [];
}

// ─── Submit order ───
export interface OrderSubmission {
  customerName: string;
  customerPhone: string;
  wilaya: string;
  address: string;
  notes: string;
  items: {
    productId: string;
    phoneModelName: string; // hardcoded model name, not DB id
    quantity: number;
    unitPrice: number;
    isCustom?: boolean;
    customDescription?: string;
    designImages?: string[]; // Firebase Storage URLs
  }[];
  totalAmount: number;
  shippingCost: number;
}

export async function submitOrder(order: OrderSubmission) {
  if (!getSupabase()) throw new Error('Supabase is not configured');

  // 1. Create the order
  const { data: orderData, error: orderError } = await supabase
    .from('orders')
    .insert({
      order_number: '', // auto-generated by trigger
      customer_name: order.customerName,
      customer_phone: order.customerPhone,
      wilaya: order.wilaya,
      address: order.address,
      notes: order.notes,
      total_amount: order.totalAmount,
      shipping_cost: order.shippingCost,
      status: 'pending',
    })
    .select('id, order_number')
    .single();

  if (orderError || !orderData) {
    console.error('Error creating order:', orderError);
    throw new Error('Failed to create order');
  }

  // 2. Create order items
  const orderItems = order.items.map(item => ({
    order_id: orderData.id,
    product_id: item.isCustom ? null : item.productId,
    phone_model_id: null, // TODO: resolve phoneModelName to phone_model_id via lookup
    quantity: item.quantity,
    unit_price: item.unitPrice,
    is_custom: item.isCustom || false,
    custom_description: item.customDescription || '',
  }));

  const { data: itemsData, error: itemsError } = await supabase
    .from('order_items')
    .insert(orderItems)
    .select('id');

  if (itemsError) {
    console.error('Error creating order items:', itemsError);
    throw new Error('Failed to create order items');
  }

  // Design images for regular orders should be uploaded to Supabase Storage

  return {
    orderId: orderData.id,
    orderNumber: orderData.order_number,
  };
}

// ─── Submit custom order (from /create personalization page) ───
export interface CustomOrderSubmission {
  customerName: string;
  customerPhone: string;
  wilaya: string;
  address: string;
  brandSlug: string;
  phoneModel: string;
  description: string;
}

export async function submitCustomOrder(order: CustomOrderSubmission) {
  if (!getSupabase()) throw new Error('Supabase is not configured');

  const { data, error } = await supabase
    .from('custom_orders')
    .insert({
      customer_name: order.customerName,
      customer_phone: order.customerPhone,
      wilaya: order.wilaya,
      address: order.address,
      brand_slug: order.brandSlug,
      phone_model: order.phoneModel,
      description: order.description,
      status: 'new',
    })
    .select('id')
    .single();

  if (error) {
    console.error('Error creating custom order:', error);
    throw new Error('Failed to create custom order');
  }

  return { orderId: (data as any)?.id };
}

// ─── Store settings (read-only from storefront) ───
export async function getStoreSetting(key: string): Promise<string> {
  if (!getSupabase()) return '';

  const { data, error } = await supabase
    .from('store_settings' as any)
    .select('value')
    .eq('key', key)
    .single();
  if (error) return '';
  return (data as any)?.value || '';
}

