import { supabase, getSupabase } from './supabase';
import type { Product } from '@/types';

// ─── Fetch active products from Supabase ───
export async function fetchProducts(): Promise<Product[]> {
  if (!getSupabase()) return [];

  // Try with product_images join first
  let data: any[] | null = null;
  let useJoin = true;

  const result = await supabase
    .from('products')
    .select('id, name, price, category, description, popular, image_url, product_images(image_url, is_primary)')
    .eq('status', 'active')
    .order('created_at', { ascending: false });

  if (result.error) {
    console.error('Error fetching products with join:', result.error);
    // Fallback: fetch without join
    useJoin = false;
    const fallback = await supabase
      .from('products')
      .select('id, name, price, category, description, popular, image_url')
      .eq('status', 'active')
      .order('created_at', { ascending: false });
    
    if (fallback.error) {
      console.error('Error fetching products:', fallback.error);
      return [];
    }
    data = fallback.data;
  } else {
    data = result.data;
  }

  return (data || []).map((p: any) => {
    let imageUrl = '/products/case-amirah.png'; // ultimate fallback

    if (useJoin) {
      const imgs = p.product_images || [];
      const primary = imgs.find((img: any) => img.is_primary);
      imageUrl = primary?.image_url || imgs[0]?.image_url || p.image_url || imageUrl;
    } else {
      imageUrl = p.image_url || imageUrl;
    }

    return {
      id: p.id,
      name: p.name,
      price: p.price,
      category: p.category as Product['category'],
      description: p.description || '',
      popular: p.popular || false,
      image: imageUrl,
    };
  });
}

// ─── Fetch shipping rates from Supabase ───
export async function fetchShippingRates() {
  if (!getSupabase()) return [];

  const { data, error } = await supabase
    .from('shipping_rates')
    .select('*')
    .order('wilaya_code');

  if (error) {
    console.error('Error fetching shipping rates:', error);
    return [];
  }

  return data || [];
}

// ─── Submit order ───
export interface OrderSubmission {
  customerName: string;
  customerPhone: string;
  wilaya: string;
  address: string;
  notes: string;
  items: {
    productId: string;
    phoneModel: string;
    customName: string;
    quantity: number;
    unitPrice: number;
    isCustom?: boolean;
    customDescription?: string;
  }[];
  totalAmount: number;
  shippingCost: number;
}

export async function submitOrder(order: OrderSubmission) {
  if (!getSupabase()) throw new Error('Supabase is not configured');

  // 1. Create the order
  const { data: orderData, error: orderError } = await supabase
    .from('orders')
    .insert({
      order_number: '', // auto-generated by trigger
      customer_name: order.customerName,
      customer_phone: order.customerPhone,
      wilaya: order.wilaya,
      address: order.address,
      notes: order.notes,
      total_amount: order.totalAmount,
      shipping_cost: order.shippingCost,
      status: 'pending',
    })
    .select('id, order_number')
    .single();

  if (orderError || !orderData) {
    console.error('Error creating order:', orderError);
    throw new Error('Failed to create order');
  }

  // 2. Create order items with all details
  const orderItems = order.items.map(item => ({
    order_id: orderData.id,
    product_id: item.isCustom ? null : (item.productId || null),
    phone_model: item.phoneModel || null,
    custom_name: item.customName || null,
    quantity: item.quantity,
    unit_price: item.unitPrice,
    is_custom: item.isCustom || false,
    custom_description: item.customDescription || null,
  }));

  const { error: itemsError } = await supabase
    .from('order_items')
    .insert(orderItems)
    .select('id');

  if (itemsError) {
    console.error('Error creating order items:', itemsError);
    throw new Error('Failed to create order items');
  }

  return {
    orderId: orderData.id,
    orderNumber: orderData.order_number,
  };
}

// ─── Submit custom order (from /create personalization page) ───
export interface CustomOrderSubmission {
  customerName: string;
  customerPhone: string;
  wilaya: string;
  address: string;
  brandSlug: string;
  phoneModel: string;
  description: string;
  photos?: File[];
}

export async function submitCustomOrder(order: CustomOrderSubmission) {
  if (!getSupabase()) throw new Error('Supabase is not configured');

  // Upload images to Supabase Storage if any
  let imageUrls: string[] = [];
  if (order.photos && order.photos.length > 0) {
    const uploadPromises = order.photos.map(async (file, index) => {
      const ext = file.name.split('.').pop() || 'jpg';
      const fileName = `${Date.now()}_${index}.${ext}`;
      const filePath = `custom-designs/${fileName}`;

      const { error: uploadError } = await supabase.storage
        .from('order-images')
        .upload(filePath, file, { contentType: file.type, upsert: false });

      if (uploadError) {
        console.error('Image upload error:', uploadError);
        return null;
      }

      const { data: urlData } = supabase.storage
        .from('order-images')
        .getPublicUrl(filePath);

      return urlData?.publicUrl || null;
    });

    const results = await Promise.all(uploadPromises);
    imageUrls = results.filter((url): url is string => url !== null);
  }

  const { data, error } = await supabase
    .from('custom_orders')
    .insert({
      customer_name: order.customerName,
      customer_phone: order.customerPhone,
      wilaya: order.wilaya,
      address: order.address,
      brand_slug: order.brandSlug,
      phone_model: order.phoneModel,
      description: order.description,
      image_urls: imageUrls.length > 0 ? imageUrls : null,
      status: 'pending',
    })
    .select('id')
    .single();

  if (error) {
    console.error('Error creating custom order:', error);
    throw new Error('Failed to create custom order');
  }

  return { orderId: (data as any)?.id };
}

// ─── Store settings (read-only from storefront) ───
export async function getStoreSetting(key: string): Promise<string> {
  if (!getSupabase()) return '';

  const { data, error } = await supabase
    .from('store_settings' as any)
    .select('value')
    .eq('key', key)
    .single();
  if (error) return '';
  return (data as any)?.value || '';
}

